### ISSUE TITLE
Feature Request - Reduce the SDK bundle size

### ISSUE THREAD

**Issue by codediodeio** [mongodb/stitch-js-sdk#117]
You guys have a really awesome product here, but a `146KB ` is too heavy to just drop into a progressive web app. It would be nice to see tree shaking or support to bring in smaller parts of the web SDK.

**Comment by edaniels** [comment]
Hey Jeff! We will definitely look into this, especially tree shaking. Are you pulling in the webpacked bundle or are you pulling in the source yourself with npm?

**Comment by codediodeio** [comment]
```
import { StitchClientFactory } from 'mongodb-stitch';
const clientPromise = StitchClientFactory.create('project...')
// bundle.js     148 kB       0  [emitted]  main
```

The web SDK script `<script src="https://s3.amazonaws.com/stitch-sdks/js/library/v3/stable/stitch.min.js"></script>` is about the same size in chrome dev tools.

**Comment by edaniels** [comment]
Hey again Jeff. We are releasing a 4.0 version of this SDK in the coming weeks. Code size should be more manageable for you now since we will publish ES modules that are not bundled up in advance. So if you can get treeshaking done with your bundler, you should get a smaller size. If not, please reopen. The current beta is at the package mongodb-stitch-browser-sdk on npm. That contains the core and the remote mongo client. You can also just install it's dependencies instead.
