### ISSUE TITLE
Unknown named module: 'mongodb-stitch-react-native-core'

### ISSUE THREAD

**Issue by michchan** [mongodb/stitch-js-sdk#166]
I encountered the following issue when I copied the sample code from https://s3.amazonaws.com/stitch-sdks/js-react-native/docs/4/index.html#installation
with react-native-init and
with mongodb-stitch-react-native-sdk and mongodb-stitch-react-native-core installed.

![image](https://user-images.githubusercontent.com/26570687/44383760-6a0af280-a54c-11e8-8d1b-dde07e0b3d90.png)

react-native-cli: 2.0.1
react-native: 0.56.0
react: 16.4.1,
mongodb-stitch-react-native-core: ^4.0.13
mongodb-stitch-react-native-sdk: ^4.0.13
node: 8.0.0

**Comment by adamchel** [comment]
Hi @michchan ,

Thank you for reaching out. React Native 0.56.0 uses a version of the React Native bundler that doesn't support UMD modules due to a bug/tradeoff that is discussed more in depth at this GitHub issue: https://github.com/facebook/metro/issues/225. Our JavaScript SDKs follow the UMD packaging convention.

I've submitted a PR to the repo for the metro bundler, so it will hopefully be fixed in a future version of React Native, but for now, feel free to use React Native 0.55.2. I was able to confirm that it works without this issue.

I will also update the peer dependency in the packages to 0.55.2 instead of 0.56.0 to reflect this incompatibility.

Let me know if you have any other questions or issues!

**Comment by adamchel** [comment]
Hi again @michchan, we've recently changed the way we expose our JS modules, which should fix your issue without requiring any workaround. 

https://github.com/mongodb/stitch-js-sdk/releases/tag/v4.1.0

As of the latest version of the Stitch JS SDK, the latest version of React Native should be supported.

Feel free to open another issue if you have any other issues using our SDK with React Native or any other JS environment.
