### ISSUE TITLE
sockets client with backend service

### ISSUE THREAD

**Issue by crobinson42** [mongodb/stitch-js-sdk#23]
Are there any solutions for connecting clients to the backend via socket connection and updating clients over the socket connection when a model or record changes?

**Comment by edaniels** [comment]
At present, no. Later this year though we are planning on integrating change streams from the MongoDB server into Stitch to be able to get realtime updates on document changes. A temporary solution right now would involve using a service like pubnub and facilitating updates through pipelines that reach out to subscribed clients.

**Comment by edaniels** [comment]
In the next month or so we will be adding a watch function to watch specific documents changing in a collection. Would this satisfy your use case?

**Comment by adrian-gierakowski** [comment]
@edaniels sounds cool. Is this going to be available in React Native?

**Comment by crobinson42** [comment]
@adrian-gierakowski I don't think react-native is an implementation detail concern for the back-end "watchers"/functions :-)

**Comment by edaniels** [comment]
Yes it will be!

**Comment by lmachens** [comment]
Does it make sense to use PubNub in a new project or is the implementation of change streams in the near future?

**Comment by adrian-gierakowski** [comment]
@edaniels: any updates regarding timeline for this feature?

**Comment by edaniels** [comment]
Should be delivering this in a few weeks. No hard date though.

**Comment by adamchel** [comment]
We have just released this feature!

See https://github.com/mongodb/stitch-js-sdk/releases/tag/v4.2.0

Unfortunately, we are not yet supporting for React Native, due to a lack of mature support for [server-event events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events) on that platform.  On the Stitch backend, we use server-sent events to implement the streaming. I have opened a proposal for React Native to add support for SSEs, and you can track and vote on that that issue here: https://github.com/react-native-community/discussions-and-proposals/issues/99

We wanted to prioritize getting this feature out for browsers and Node.js, but if you're still interesting in having this feature in React Native, please open another issue in this repo and we'll look into supporting it ourselves and robustly testing it using the polyfills that exist today.

**Comment by boustanihani** [comment]
@adamchel according to: https://docs.mongodb.com/stitch-sdks/js-server/4/interfaces/remotemongocollection.html#watch

**... Please note that this method does not support opening change streams on an entire collection or a specific query. The documents to watch must be explicitly specified by their _id ...**

Will opening change streams on an entire collection be possible in the near future?
